name: use Docker in GHA
on: [workflow_dispatch]
jobs:
    job1:
        runs-on: ubuntu-latest
        container: #add alpine node version
            image: node:14-alpine  
        steps:
            - name: Check Node version and OS version
              run: |
                node --version
                cat /etc/os-release
            - name: container for step
              uses: docker://node:14-alpine
              with:
                  entrypoint: D:\VS_node_JS\node.exe
                  args: |
                      -p 2 + 3
            - name: container steps 2   
              uses: docker://node:16-alpine
              with:
                  args: --version

